[tool.pdm]
# handle version dynamic
version = {source = "file", path = "py_dev_init/__init__.py"}

[project.optional-dependencies]
# make pip able to install the dev
# $ pip install .[dev]
# we don't want to use PEP 582 or virtualenv
dev = [
    "black",
    "docs-helper",
    "pytest",
    "rinohtype",
    "ruff",
    "sphinx-autobuild",
    "sphinx-copybutton",
    "sphinx-rtd-theme",
    "Sphinx",
    "sphinxcontrib-autoprogram",
    "sphinxcontrib.kroki",
]

[project]
authors = [{name = "Viktor Freiman", email = "freiman.viktor@gmail.com"}]
dependencies = ["requests>=2.28.1"]
description = "Kickstart repo, change this"
dynamic = ["version"]
license = {text = "MIT"}
name = "py-dev-init"
readme = "README.md"
requires-python = ">=3.10"

[build-system]
build-backend = "pdm.pep517.api"
requires = ["pdm-pep517>=1.0"]
