[tool.poetry]
name = "py-dev-init"
version = "0.3.0"
description = "Kickstart repo"
authors = ["Viktor Freiman <freiman.viktor@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.2"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
flake8 = "^4.0.1"
flake8-bugbear = "^21.9.2"
flake8-quotes = "^3.3.1"
rinohtype = "^0.5.3"
Sphinx = "^4.2.0"
sphinx-argparse = "^0.3.1"
sphinx-autobuild = "^2021.3.14"
sphinx-rtd-theme = "^1.0.0"
sphinxcontrib-kroki = "^1.3.0"
toml = "^0.10.2"
sphinx-copybutton = "^0.5.0"
docs-helper = "^0.0.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
